version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: security_app
      MYSQL_ROOT_PASSWORD: django_password
      MYSQL_USER: django
      MYSQL_PASSWORD: django_password
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fullstack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: django_password
    ports:
      - "8082:80"
    networks:
      - fullstack

  ethicalpulse-backend:
    build:
      context: ./backend
    container_name: ethicalpulse-backend  # Nom corrigé pour être cohérent
    restart: always
    entrypoint: ["/app/wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend/ethicalpulse:/app  # Vérifiez que cela correspond à la structure de votre projet
      - ./backend/wait-for-it.sh:/app/wait-for-it.sh  # Ajouté pour s'assurer que le script est accessible
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://django:django_password@db:3306/security_app
    networks:
      - fullstack

  ethicalpulse-frontend:
    build:
      context: ./frontend
    container_name: ethicalpulse-frontend  # Nom corrigé pour être cohérent
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    depends_on:
      - ethicalpulse-backend
    networks:
      - fullstack

volumes:
  db_data:

networks:
  fullstack:
    driver: bridge